<!doctype html>
<html ng-app="Categorias">
<head>
    <title>ZF2+Angular</title>
    <link href="css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
    <meta charset="UTF-8" />
</head>
<body>

    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
        <a class="brand" href="#">AngularJS</a>
                <ul class="nav">
                  <li class="active">
                    <a href="#">Home</a>
                  </li>
                  <li><a href="#">Categoria</a></li>
                  <li><a href="#">Produtos</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="page-header" ng-controller="CategoriasController">
            <br />
            <br />
            <div ng-view></div>
        </div>

        <div class="footer">
            <div class="container">
                <p class="text-muted credit">Teste Footer</p>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular-route.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular-resource.min.js"></script>
    <script src="projetoangular/Categorias.js"></script>
    <script src="projetoangular/CategoriasController.js"></script>
    <script src="projetoangular/CategoriasSrv.js"></script>
</body>
</html>